version: '3.2'
services:
  chat-app:
    build: ./chat-app
    env_file: .env
    volumes:
      - ./chat-app:/chat-app
    depends_on:
      - db
      - elasticsearch
      - redis
    ports:
      - 3000:3000

  chat-creation-endpoint:
    build: ./chat-creation-endpoint
    volumes:
      - ./chat-creation-endpoint:/go/src/chat-creation-endpoint
    depends_on:
      - redis
    ports:
      - 3001:3001
      
  db:
    image: mysql:5.7
    env_file: .env
  
  elasticsearch:
    image: elasticsearch:6.4.0

  redis:
    image: redis:alpine